[package]
name = "elx"
version = "0.1.2"
edition = "2024"
description = "Fast and customizable personal ls replacement written in Rust"
license = "MIT"
repository = "https://github.com/rozeraf/elx"
homepage = "https://github.com/rozeraf/elx"
readme = "README.md"

[dependencies]
anyhow = "1.0.102"
chrono = "0.4.44"
clap = { version = "4.6.1", features = ["derive"] }
crossterm = "0.29.0"
dirs = "6.0.0"
figment = { version = "0.10.19", features = ["toml", "env"] }
gix = "0.70.0"
ignore = "0.4.25"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
terminal_size = "0.4.4"
toml = "1.1.2"
toml_edit = "0.22"
unicode-width = "0.2.2"
users = "0.11.0"
